class_name AppPolicy
extends RefCounted

const OFFLINE_REPORT_THRESHOLD_SECONDS := 120
const OFFLINE_CAP_SECONDS := 8 * 60 * 60
const OFFLINE_TICK_CHUNK_SECONDS := 60.0
const PERIODIC_SAVE_SECONDS := 30.0
const BOOT_STATUS_DELAY_MSEC := 300
const GAMEPLAY_TAB_MIN := 0
const GAMEPLAY_TAB_MAX := 2
